from sqlalchemy import create_engine, Column, Integer, String, DateTime, ForeignKey, Boolean, Text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship
from datetime import datetime
import os

# --- 1. Database Configuration ---
# This variable comes from the DATABASE_URL in our .env file, loaded by main.py
DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise Exception("DATABASE_URL is not set. Cannot connect to database.")

# Create the engine, which manages the connection pool
engine = create_engine(DATABASE_URL)

# Create a base class for declarative class definitions
Base = declarative_base()

# Create a configured "Session" class
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


# --- 2. Database Models ---

class User(Base):
    """
    Represents a user account for subscription and credit gating.
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String, unique=True, index=True) # The ID received from the extension
    email = Column(String, unique=True, nullable=True)
    
    # Monetization Fields (Core of Phase 3)
    subscription_tier = Column(String, default="free") # e.g., 'free', 'pro', 'team'
    idea_credits = Column(Integer, default=5)          # Credits for the free tier
    is_active = Column(Boolean, default=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationship to the ideas generated by this user
    ideas = relationship("Idea", back_populates="owner")


class Idea(Base):
    """
    Represents a single startup idea generated by the LLM.
    """
    __tablename__ = "ideas"

    id = Column(Integer, primary_key=True, index=True)
    
    # Foreign Key linking the idea back to the user
    owner_id = Column(Integer, ForeignKey("users.id"))
    
    name = Column(String, index=True)
    problem = Column(Text)
    solution = Column(Text)
    source_url = Column(String, nullable=True) # The URL the idea was generated from
    
    generated_at = Column(DateTime, default=datetime.utcnow)

    # Relationship linking back to the user object
    owner = relationship("User", back_populates="ideas")


# --- 3. Database Utility ---

def get_db():
    """
    Dependency to create a new, independent database session/connection 
    for each request, ensuring it's closed afterward. Used in main.py.
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

def create_database_tables():
    """
    Creates all defined tables in the database. Called once on application startup.
    """
    # This command uses the Base metadata to create the actual tables in Postgres
    Base.metadata.create_all(bind=engine)
    print("Database tables checked/created successfully.")